# Generated by Django 4.0.4 on 2022-06-03 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corporativo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='NOME')),
                ('dataadmissao', models.DateField(verbose_name='DATA DE ADMISSÃO')),
                ('obs', models.TextField(max_length=500, verbose_name='OBSERVAÇÃO')),
                ('name_dep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corporativo.departamento', verbose_name='DEPARTAMENTO')),
                ('name_function', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corporativo.funcao', verbose_name='FUNÇÃO')),
            ],
            options={
                'verbose_name': 'COLABORADOR',
                'verbose_name_plural': 'COLABORADORES',
            },
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_init', models.DateField(verbose_name='DATA INICIAL')),
                ('date_finish', models.DateField(verbose_name='DATA FINAL')),
                ('obs', models.TextField(max_length=400, verbose_name='OBSERVAÇÃO')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corporativo.funcao', verbose_name='FUNÇÃO')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dep_pessoal.funcionario', verbose_name='NOME')),
            ],
            options={
                'verbose_name': 'Falta',
                'verbose_name_plural': 'FALTAS',
            },
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50, verbose_name='CLIENTE')),
                ('type_att', models.CharField(choices=[('MANUTENÇÃO', 'MANUTENÇÃO'), ('INSTALAÇÃO', 'INSTALAÇÃO')], max_length=15, verbose_name='SERVIÇO')),
                ('date_init', models.DateField(verbose_name='DATA ATENDIMENTO')),
                ('obs', models.TextField(max_length=500, verbose_name='OBSERVAÇÃO')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corporativo.funcao', verbose_name='FUNÇÃO')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dep_pessoal.funcionario', verbose_name='TÉCNICO')),
            ],
            options={
                'verbose_name': 'PLANTÃO EXTRA',
                'verbose_name_plural': 'PLANTÕES EXTRAS',
            },
        ),
        migrations.CreateModel(
            name='Atestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_init', models.DateField(verbose_name='DATA INICIAL')),
                ('date_finish', models.DateField(verbose_name='DATA FINAL')),
                ('obs', models.TextField(max_length=400, verbose_name='OBSERVAÇÃO')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corporativo.funcao', verbose_name='FUNÇÃO')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dep_pessoal.funcionario', verbose_name='NOME')),
            ],
            options={
                'verbose_name': 'ATESTADO',
                'verbose_name_plural': 'ATESTADOS',
            },
        ),
    ]
