# Generated by Django 4.0.4 on 2022-06-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep_pessoal', '0002_falta_cid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='falta',
            name='cid',
        ),
        migrations.AddField(
            model_name='atestado',
            name='cid',
            field=models.CharField(default=1, max_length=8, verbose_name='CID'),
            preserve_default=False,
        ),
    ]
