# Generated by Django 4.0.4 on 2022-08-25 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporativo', '0001_initial'),
        ('dep_pessoal', '0003_remove_falta_cid_atestado_cid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispensaLiberado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_init', models.DateField(verbose_name='DATA INICIAL')),
                ('date_finish', models.DateField(verbose_name='DATA FINAL')),
                ('obs', models.TextField(max_length=400, verbose_name='OBSERVAÇÃO')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corporativo.funcao', verbose_name='FUNÇÃO')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dep_pessoal.funcionario', verbose_name='NOME')),
            ],
            options={
                'verbose_name': 'DISPENSA / LIBERAÇÃO',
                'verbose_name_plural': 'DISPENSA / LIBERAÇÃO',
            },
        ),
    ]
