# Generated by Django 4.0.4 on 2022-06-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_dep', models.CharField(max_length=40, verbose_name='DEPARTAMENTO')),
            ],
            options={
                'verbose_name': 'DEPARTAMENTO',
                'verbose_name_plural': 'DEPARTAMENTOS',
            },
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_function', models.CharField(max_length=40, verbose_name='FUNÇÃO')),
            ],
            options={
                'verbose_name': 'FUNÇÃO',
                'verbose_name_plural': 'FUNÇÕES',
            },
        ),
    ]
