# Generated by Django 4.0.4 on 2022-06-12 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dep_pessoal', '0003_remove_falta_cid_atestado_cid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleKm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('da_ta', models.DateField(verbose_name='DATA')),
                ('km_init', models.IntegerField(verbose_name='KM INICIAL')),
                ('km_end', models.IntegerField(verbose_name='KM FINAL')),
            ],
            options={
                'verbose_name': 'CONTROLE DE KM',
                'verbose_name_plural': 'CONTROLE DE KMs',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=30, verbose_name='MODELO')),
                ('collor', models.CharField(max_length=30, verbose_name='COR')),
                ('year', models.IntegerField(verbose_name='ANO')),
                ('autonomy', models.IntegerField(verbose_name='AUTONOMIA/CONSUMO')),
            ],
            options={
                'verbose_name': 'VEICULO',
                'verbose_name_plural': 'VEICULOS',
            },
        ),
        migrations.CreateModel(
            name='Condutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CONDUTOR', to='dep_pessoal.funcionario', verbose_name='MOTORISTA')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='VEICULO', to='controle_km.vehicle')),
            ],
            options={
                'verbose_name': 'CONTROLE DE KM',
                'verbose_name_plural': 'CONTROLE DE KMs',
            },
        ),
    ]
