# Generated by Django 4.0.4 on 2022-06-12 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle_km', '0002_alter_condutor_options_controlekm_condutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlekm',
            name='tot_km',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n', verbose_name='KM RODADO'),
            preserve_default=b'I01\n',
        ),
        migrations.AlterField(
            model_name='condutor',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='VEICULO', to='controle_km.vehicle', verbose_name='VEICULO'),
        ),
    ]
