# Generated by Django 4.0.4 on 2022-08-25 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_km', '0003_controlekm_tot_km_alter_condutor_vehicle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlekm',
            options={'ordering': ['da_ta'], 'verbose_name': 'CONTROLE DE KM', 'verbose_name_plural': 'CONTROLE DE KMs'},
        ),
    ]
