# Generated by Django 4.0.4 on 2022-07-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistoria',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Data Inicio'),
        ),
    ]
