# Generated by Django 4.0.4 on 2022-06-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistoria',
            name='alteration',
            field=models.BooleanField(default=1, verbose_name='COM ALTERAÇÃO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vistoria',
            name='no_alteration',
            field=models.BooleanField(default=1, verbose_name='SEM ALTERAÇÃO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vistoria',
            name='obs',
            field=models.TextField(default=1, max_length=1000, verbose_name='OBSERVAÇÃO'),
            preserve_default=False,
        ),
    ]
