# Generated by Django 4.0.4 on 2022-06-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_vistoria_alteration_vistoria_no_alteration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteorcamento',
            name='obs',
            field=models.TextField(default=1, max_length=1000, verbose_name='OBSERVAÇÃO'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='no_alteration',
            field=models.BooleanField(default=True, verbose_name='SEM ALTERAÇÃO'),
        ),
    ]
