# Generated by Django 4.0.4 on 2022-06-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_clienteorcamento_obs_alter_vistoria_no_alteration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vistoria',
            old_name='obs',
            new_name='obs_eqp_alter',
        ),
        migrations.AddField(
            model_name='vistoria',
            name='obs_implant_alter',
            field=models.TextField(default=1, max_length=1000, verbose_name='OBSERVAÇÃO'),
            preserve_default=False,
        ),
    ]
