# Generated by Django 4.0.4 on 2022-06-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_rename_obs_vistoria_obs_eqp_alter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistoria',
            name='obs_service_alter',
            field=models.TextField(default=1, max_length=1000, verbose_name='OBSERVAÇÃO'),
            preserve_default=False,
        ),
    ]
