# Generated by Django 4.0.4 on 2022-06-09 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_vistoria_obs_service_alter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistoria',
            name='obs_eqp_alter',
            field=models.TextField(max_length=1000, verbose_name='OBSERVAÇÃO DE EQUIPAMENTOS'),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='obs_implant_alter',
            field=models.TextField(max_length=1000, verbose_name='OBSERVAÇÃO DE IMPLANTAÇÃO'),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='obs_service_alter',
            field=models.TextField(max_length=1000, verbose_name='OBSERVAÇÃO DE SERVIÇO'),
        ),
    ]
