# Generated by Django 4.0.4 on 2022-06-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronogramaOsInstalacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_os', models.IntegerField(verbose_name='Nº O.S')),
                ('code_client', models.CharField(max_length=40, verbose_name='COD - Cliente')),
                ('team', models.CharField(max_length=50, verbose_name='Equipe')),
                ('date_start', models.DateField(verbose_name='Data Inicio')),
                ('date_end', models.DateField(verbose_name='Data Fim')),
                ('date_delivery', models.DateField(verbose_name='Data Entrega')),
                ('status', models.CharField(choices=[('AGENDADO', 'AGENDADO'), ('NÃO INICIADO', 'NÃO INICIADO'), ('INICIADO', 'INICIADO'), ('PAUSADO', 'PAUSADO'), ('FINALIZADO', 'FINALIZADO'), ('ENTREGUE', 'ENTREGUE')], default='NÃO INICIADO', max_length=15, verbose_name='Status')),
                ('service', models.CharField(choices=[('CFTV', 'CFTV'), ('CFTV - ALARME', 'CFTV - ALARME'), ('CFTV - CERCA E.', 'CERCA E.'), ('CFTV - CONTROLE DE ACE.', 'CFTV - CONTROLE DE ACE.'), ('ALARME', 'ALARME'), ('ALARME - CERCA E.', 'ALARME - CERCA E.'), ('ALARME - CONTROLE DE ACE.', 'ALARME - CONTROLE DE ACE.'), ('CERCA ELÉTRICA', 'CERCA ELÉTRICA'), ('CERCA E. - CONTROLE DE ACE.', 'CERCA E. - CONTROLE DE ACE.'), ('CONTROLE DE ACESSO', 'CONTROLE DE ACESSO'), ('ALARME - CERCA - CONT. ACE. - CFTV', 'ALARME - CERCA - CONT. ACE. - CFTV')], default='ALARME', max_length=40, verbose_name='Serviço(s)')),
            ],
            options={
                'verbose_name': 'CONTROLE DE O.S',
                'verbose_name_plural': 'CONTROLE DE O.S',
            },
        ),
    ]
