# Generated by Django 4.0.4 on 2022-05-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronogramaOsInstalacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_os', models.IntegerField(verbose_name='Nº O.S')),
                ('code_client', models.IntegerField(verbose_name='COD - Cliente')),
                ('team', models.CharField(max_length=50, verbose_name='Equipe')),
                ('date_start', models.DateField(verbose_name='Data Inicio')),
                ('date_end', models.DateField(verbose_name='Data Fim')),
                ('date_delivery', models.DateField(verbose_name='Data Entrega')),
                ('status', models.CharField(choices=[('Não iniciado', 'Não iniciado'), ('Iniciado', 'Iniciado'), ('Pausado', 'Pausado'), ('Finalizado', 'Finalizado')], default='Não Iniciado', max_length=15, verbose_name='Status')),
                ('service', models.CharField(choices=[('Cftv', 'Cftv'), ('Cftv + Alarme', 'Cftv + Alarme'), ('Cftv + Cerca E.', 'Cerca E.'), ('Cftv + Controle de A.', 'Cftv + Controle de A.'), ('Alarme', 'Alarme'), ('Alarme + Cerca E.', 'Alarme + Cerca E.'), ('Alarme + Controle de A.', 'Alarme + Controle de A.'), ('Cerca Elétrica', 'Cerca Elétrica'), ('Cerca E. + Controle de A.', 'Cerca E. + Controle de A.'), ('Controle de Acesso', 'Controle de Acesso'), ('Todos os Serviço', 'Todos os Serviço')], default='Alarme', max_length=30, verbose_name='Serviço(s)')),
            ],
        ),
    ]
