# Generated by Django 4.0.4 on 2022-06-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_controle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronogramaosinstalacao',
            name='boto',
            field=models.IntegerField(default=0, verbose_name='BOTOEIRA'),
        ),
        migrations.AddField(
            model_name='cronogramaosinstalacao',
            name='cam',
            field=models.IntegerField(default=0, verbose_name='CÂMERA'),
        ),
        migrations.AddField(
            model_name='cronogramaosinstalacao',
            name='central',
            field=models.IntegerField(default=0, verbose_name='CENTRAL DE ALARME'),
        ),
        migrations.AddField(
            model_name='cronogramaosinstalacao',
            name='dvr',
            field=models.IntegerField(default=0, verbose_name='DVR/NVR'),
        ),
        migrations.AddField(
            model_name='cronogramaosinstalacao',
            name='eletrific',
            field=models.IntegerField(default=0, verbose_name='CENTRAL DE CHOQUE'),
        ),
        migrations.AddField(
            model_name='cronogramaosinstalacao',
            name='eletroi',
            field=models.IntegerField(default=0, verbose_name='ELETROIMÃ'),
        ),
        migrations.AddField(
            model_name='cronogramaosinstalacao',
            name='fonte',
            field=models.IntegerField(default=0, verbose_name='FONTE DE ALIMENTAÇÃO'),
        ),
        migrations.AddField(
            model_name='cronogramaosinstalacao',
            name='haste_cerca',
            field=models.IntegerField(default=0, verbose_name='HASTE DE CERCA'),
        ),
        migrations.AddField(
            model_name='cronogramaosinstalacao',
            name='interphon',
            field=models.IntegerField(default=0, verbose_name='INTERFONE'),
        ),
        migrations.AddField(
            model_name='cronogramaosinstalacao',
            name='iva',
            field=models.IntegerField(default=0, verbose_name='SENSOR DE BARREIRA'),
        ),
        migrations.AddField(
            model_name='cronogramaosinstalacao',
            name='ivp',
            field=models.IntegerField(default=0, verbose_name='SENSOR DE PRESENÇA'),
        ),
        migrations.AddField(
            model_name='cronogramaosinstalacao',
            name='leit_digita',
            field=models.IntegerField(default=0, verbose_name='LEITOR DIGITAL/FACIAL'),
        ),
        migrations.AddField(
            model_name='cronogramaosinstalacao',
            name='mag',
            field=models.IntegerField(default=0, verbose_name='SENSOR DE MAGNETICO'),
        ),
        migrations.AddField(
            model_name='cronogramaosinstalacao',
            name='mola_air',
            field=models.IntegerField(default=0, verbose_name='MOLA AÉREA'),
        ),
        migrations.AddField(
            model_name='cronogramaosinstalacao',
            name='motor_gate',
            field=models.IntegerField(default=0, verbose_name='MOTOR DE PORTÃO'),
        ),
        migrations.AddField(
            model_name='cronogramaosinstalacao',
            name='radio',
            field=models.IntegerField(default=0, verbose_name='RADIO OUTDOOR'),
        ),
        migrations.AddField(
            model_name='cronogramaosinstalacao',
            name='raque',
            field=models.IntegerField(default=0, verbose_name='RAQUE'),
        ),
    ]
