# Generated by Django 4.0.4 on 2022-07-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_controle', '0002_cronogramaosinstalacao_boto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronogramaosinstalacao',
            name='raque1',
            field=models.ImageField(default=0, upload_to='', verbose_name='RAQUE CFTV'),
        ),
    ]
