# Generated by Django 4.0.4 on 2022-05-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_controle', '0003_alter_cronogramaosinstalacao_service_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cronogramaosinstalacao',
            options={'verbose_name': 'CONTROLE DE O.S', 'verbose_name_plural': 'CONTROLE DE O.S'},
        ),
        migrations.AlterField(
            model_name='cronogramaosinstalacao',
            name='service',
            field=models.CharField(choices=[('CFTV', 'CFTV'), ('CFTV - ALARME', 'CFTV - ALARME'), ('CFTV - CERCA E.', 'CERCA E.'), ('CFTV - CONTROLE DE ACE.', 'CFTV - CONTROLE DE ACE.'), ('ALARME', 'ALARME'), ('ALARME - CERCA E.', 'ALARME - CERCA E.'), ('ALARME - CONTROLE DE ACE.', 'ALARME - CONTROLE DE ACE.'), ('CERCA ELÉTRICA', 'CERCA ELÉTRICA'), ('CERCA E. - CONTROLE DE ACE.', 'CERCA E. - CONTROLE DE ACE.'), ('CONTROLE DE ACESSO', 'CONTROLE DE ACESSO'), ('ALARME - CERCA - CONT. ACE. - CFTV', 'ALARME - CERCA - CONT. ACE. - CFTV')], default='ALARME', max_length=40, verbose_name='Serviço(s)'),
        ),
        migrations.AlterField(
            model_name='cronogramaosinstalacao',
            name='status',
            field=models.CharField(choices=[('NÃO INICIADO', 'NÃO INICIADO'), ('INICIADO', 'INICIADO'), ('PAUSADO', 'PAUSADO'), ('FINALIZADO', 'FINALIZADO'), ('ENTREGUE', 'ENTREGUE')], default='NÃO INICIADO', max_length=15, verbose_name='Status'),
        ),
    ]
